name: ci-cd-pipeline
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK for backend
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: Build Backend
        run: mvn clean install

      - name: Install Angular dependencies
        run: npm install

      - name: Run Frontend Tests
        run: npm run test -- --watch=false

      - name: Run Backend Tests
        run: mvn test

      - name: Deploy to Staging (optional)
        run: |
          echo "Deploying to staging server..."
          # Your deployment command here

      - name: Push changes to GitHub
        run: git push
